name: eclipsear
description: Eclipse Explorer.
publish_to: 'none' 

version: 1.2.2+12

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.1
  buttons_tabbar: ^1.3.6
  shared_preferences: ^2.2.0
  location: ^5.0.0
  geocoding: ^2.2.2
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.2.0
  sliding_up_panel: ^2.0.0+1
  csc_picker: ^0.2.7
  video_player: ^2.7.1
  flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/elogo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/eclipses/
    - assets/json/

  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
